version: '3.9'

services:
 
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - /app/node_modules
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db

volumes:
  mysql-db: